### ISSUE TITLE
Improve process termination when changes are detected

### ISSUE THREAD

**Issue by kewegner** [appsody/controller#16]
Many stacks have ON_CHANGE commands that end the process by themselves and there is no need to kill them.

Currently the controller tries to kill them in this case, and prints out warning messages which say the kill failed and there is no such process

Outcome desired:
Either:
1.  suppress the above messages

or 

*2. Use a similar technique that we use to determine server failures and restarts in the on change events where we send a benign signal to determine if the process is alive.
Then we could avoid unnecessary kill actions.

**Comment by neeraj-laad** [comment]
@kewegner Would like to get your thoughts on this issue.

**Comment by kewegner** [comment]
This will be dealt with by the fix I'm making for https://github.com/appsody/appsody/issues/118
