### ISSUE TITLE
Should the file watcher run during APPSODY_PREP?

### ISSUE THREAD

**Issue by kewegner** [appsody/controller#34]
Currently we launch the watcher async right after we launch the RUN command which in turn does APPSODY_PREP.

We should pull out APPSODY_PREP so it runs sync prior to any of this.  OR we should update the run commands logic to spin the func for watching after APPSODY_PREP runs,

**Comment by kewegner** [comment]
@neeraj-laad can you think of any reason we would need the file watcher (and thus on-change actions) running during APPSODY_PREP?

Making the change to not run file watching during APPSODY_PREP start up is a simple matter.

BTW: There was also another issue where Henry Nash suggested running APPSODY_PREP prior every ON_CHANGE action, but I think the performance of that would be very bad.

**Comment by neeraj-laad** [comment]
@kewegner We do not need to run the watcher during the prep or install steps.
