### ISSUE TITLE
File Watcher can not see cached volumes changes

### ISSUE THREAD

**Issue by kewegner** [appsody/controller#35]
If one makes a change in the DEPS directory it is not seen by the watcher.

At this moment all DEPS directory related changes are to be IGNORED in existing stacks, however, this may change in new stacks in the future.

It is not known what the root cause of this is ATM.

**Comment by kylegc** [comment]
Do you think this has anything to do with the inotify stuff the codewind people were talking about?

**Comment by kewegner** [comment]
I am not sure, but since we don't use directly us inotify in the watcher code, I don't think so.  Unless something in golang is using it under the covers.  It seems like the watcher code is basically listing all files and then looking at their attribute timestamps, as opposed to being notified by the file system.

**Comment by kewegner** [comment]
Update:
I have been able to see changes for nodejs-express in the 
/project/user-app/node_modules directory with a modified set up.

I will continue to investigate.

**Comment by kewegner** [comment]
I do not believe this is an issue.  I reviewed the remaining stacks, I think if it works for nodejs-express it should not be a problem with the others.
