### ISSUE TITLE
Document that the watcher package does not follow symlinks when watching.

### ISSUE THREAD

**Issue by kewegner** [appsody/controller#37]
We need to review and discuss this. Question.

**Comment by kewegner** [comment]
As of yet we have not encountered a problem with symlinks and the watcher.

**Comment by kewegner** [comment]
I am working on README comments for this and will have done by Friday.

**Comment by helenmasters** [comment]
@rykal-nate are you intending to test this out, or are we just looking to add wordin, as if so I'd suggest adding something like:

"The use of symlinks within the directories that the controller monitors for file changes might result in undefined behavior."

to the README?

**Comment by rykal-nate** [comment]
@helenmasters - Yes, I did a bit of testing yesterday, the behavior is a bit nuanced and not worth documenting every individual scenario IMO.  In large, edit actions on sym links are not recognized by the controller such as document edits, renames etc ...  however if you deleted a symbolic link on a watched directory there would be a directory event.  I think the text you have is sufficient. 

I question if this should be documented with the stack env variables possibly or point to this controller notice from that location.   @neeraj-laad maybe state its not a best practice to use symbolic links as it relates to changing stack artifacts in addition? 

Thanks!
