### ISSUE TITLE
Support Creation of Docker image to copy controller 

### ISSUE THREAD

**Issue by kewegner** [appsody/controller#48]
**Describe the solution you'd like**
- Change .travis.yml to support the process
- .travis.yml Call script build.sh as part of deploy
- Create build.sh script to build docker image and push it
- Update Travis variables for Docker hub (org, user, pwd)
- setController contributed script which will copy the appsody-controller to shared volume

**Describe alternatives you've considered**
See Appsody Issues

**Comment by neeraj-laad** [comment]
@kewegner I'm closing this issue as the PR is now merged. Please re-open if there is additional work for this issue.
