### ISSUE TITLE
How to proceed with "appsody-controller" by using latest "appsody" binary for ppc64le?

### ISSUE THREAD

**Issue by vrushaliinamdar** [appsody/controller#62]
Hi Team,

This question is with reference to the enhancement request raised few days back - https://github.com/appsody/controller/issues/59

As I am a bit new to appsody and appsody-controller, please guide me on how can I work with ppc64le specific "appsody-controller" binary by leveraging the recently released "appsody" binary.

The link for appsody binary download is - https://github.com/appsody/appsody/releases/download/0.5.3/appsody-0.5.3-linux-ppc64le.tar.gz

Regards,
Vrushali

**Comment by vrushaliinamdar** [comment]
Can someone please respond to this?

**Comment by neeraj-laad** [comment]
The appsody controller will only run inside an appsody container. This should not be dependent upon the platform you are running on. 

Are you seeing any errors while running on ppc64> Please can you provide more details on what you are trying and what issue you are facing.

**Comment by neeraj-laad** [comment]
Closing this due to lack of further information. Please re-open if this is still valid issue
