### ISSUE TITLE
When APPSODY_<RUN/TEST/DEBUG>_KILL is false, and the server process doesn't exist, the server should be restarted

### ISSUE THREAD

**Issue by kewegner** [appsody/controller#7]
@kylegc raised this issue.  This could happen if Jane has a bug in her code that prevents the server from starting, or the server crashed unexpectedly. The controller would still be watching for Jane to fix the issue with a file change, however the ON_CHANGE action will not be enough to start the server back up. In this scenario, the controller should run the start server command instead of the ON_CHANGE command.

An alternative solution is to watch for the server process to exit, and then exit the controller and container. This would require Jane to fix the code and re-run appsody dev run to restart the container.

**Comment by kewegner** [comment]
The proposed solution is to check if the server is alive every time an "ON_CHANGE" action occurs.
By sending SIG 0 to the server process, one can determine whether the process is alive without actually changing the state of the process. The call will return an error if there is no process.  In this case the controller will run the command associated with APPSODY_<RUN/DEBUG/TEST> action rather than the APPSODY_<action>_ON_CHANGE command as specified in the docker file.

**Comment by tnixa** [comment]
Test to surface the problem...
1. appsody init java-microprofile
2. appsody run
3. changing src/main/java/dev/appsody/starter/health/StarterHealth.java to cause a compile error
4. appsody stop
5. appsody run -> shows the compile error
6. fixing the file to be valid again -> console shows the `BUILD SUCCESS` but the web app doesn't reload

**Comment by kewegner** [comment]
This problem goes beyond just server Start (APPSODY_RUN), as Terrance points out, in java-microprofile, it is the INSTALL that fails due to the compile error, not the RUN.  So I added prototype code for the on change to detect if INSTALL failed and do a re-run of the INSTALL action prior to running the on-change action.  We noticed when we did this, we saw some errors coming from the stack that we hadn't seen before.  tnixa will past those in this discussion as well.  

Another thing we may want to consider is if the INSTALL failed, should we kill the server, even if KILL is false.  Otherwise how do we know if the environment is really in pristine shape after doing the reinstall.

We did appear to fix the original issue with the experimental fix, at least for the Spring stack.

**Comment by kewegner** [comment]
There is a side effect to killiing and restarting the server for spring boot2.  Thereafter when a CHANGE is detected, the pack recompile produces this error, which despite the error, the server is up and the change is reflected (assuming its a good change).

ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [application.Main]; nested exception is java.io.FileNotFoundException: class path resource [application/Main.class] cannot be opened because it does not exist
[Container] 2019-07-12 13:29:22.977 ERROR 205 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed


This is the same error one  code exists that doesn't compile after a good server start, the difference is this error only happens once and doesn't happen after the code is fixed.  If we restart the server, this error occurs on every detected change.

**Comment by kylegc** [comment]
I think we need to better define and document the purpose of the APPSODY_INSTALL command. 

### Background
We added the APPSODY_INSTALL option to separate the `npm install` and `npm start` commands mainly because killing the npm install command would leave a bad, unrecoverable state. Thus we run `npm install` in the APPSODY_INSTALL and don't start the watcher until this command finishes.

APPSODY_INSTALL also gave us a cleaner dockerfile and flexibility to reuse this command in the future.

### Relation to this Issue
As @kewegner points out above, the install command may impact the ability for the server to recover from errors. We need to determine in this issue if the install command fails, should we retry it later with the ON_CHANGE command?

### Discussion Items
* Should appsody continue to run (or quit) if APPSODY_INSTALL fails?
* Should the controller retry running APPSODY_INSTALL later (such as before ON_CHANGE) if it had initially failed?
* Should APPSODY_INSTALL only be gathering dependencies or is it okay to be compiling project code?
* How do we best document the purpose and use of APPSODY_INSTALL?

**Comment by kewegner** [comment]
Note: Another potential issue is this if we try to kill the server after a failed install:
It appears that stopping the server, there is a 30 second wait in java-microprofile.  The server still came up.
[Container] [INFO] [AUDIT   ] CWWKE0055I: Server shutdown requested on Friday, July 12, 2019 at 5:14 PM. The server defaultServer is shutting down.
[Container] [INFO] [ERROR   ] CWWKZ0002E: An exception occurred while starting the application starter-app. The exception message was: com.ibm.ws.container.service.state.StateChangeException: java.util.concurrent.RejectedExecutionException: CWWKE1202E: A task cannot be submitted because the executor managedExecutorService[DefaultManagedExecutorService] (concurrencyPolicy[defaultConcurrencyPolicy]) has been shut down.

**Comment by kewegner** [comment]
Design Decision:
We will exit the controller process if INSTALL fails.
We will deprecate the environment variable APPSODY_INSTALL in favor of APPSODY_PREP.
APPSODY_INSTALL will continue to be supported in the near term.

**Comment by kylegc** [comment]
A couple more notes on the design decisions:
- By default we will exit the controller and appsody container if PREP fails, however we may add an optional flag to "skip-prep" or "ignore-prep-errors" in the future
- We should document that we do not recommend compiling code in PREP
- We will never retry running PREP
- We will create better documentation for all the stack env variables
